import Mock from 'mockjs'

let List=[]
export default {
  getStatisticalData:() => {
    for(let i=0;i<7;i++){
      List.push(
        Mock.mock({
          apple:Mock.Random.float(100,8000,0,0),
          vivo:Mock.Random.float(100,8000,0,0),
          oppo:Mock.Random.float(100,8000,0,0),
          meizu:Mock.Random.float(100,8000,0,0),
          sanxing:Mock.Random.float(100,8000,0,0),
          mi:Mock.Random.float(100,8000,0,0),

        })
      )
    }
    return {
      code:20000,
      data:{
        //饼图
        videoData:[
          {
            name:'apple',
            value:2999
          },
          {
            name:'vivo',
            value:2999
          },
          {
            name:'oppo',
            value:2999
          },
          {
            name:'meizu',
            value:2999
          },
          {
            name:'三星',
            value:2999
          },
          {
            name:'小米',
            value:2999
          },
        ],
        //柱状图
        userData:[
          {
            data:'周一',
            new:5,
            active:200
          },
          {
            data:'周二',
            new:15,
            active:200
          },
          {
            data:'周三',
            new:25,
            active:200
          },
          {
            data:'周四',
            new:35,
            active:200
          },
          {
            data:'周五',
            new:45,
            active:200
          },
          {
            data:'周六',
            new:55,
            active:200
          },
          {
            data:'周日',
            new:75,
            active:200
          },
        ],
        //折线图
        orderData:{
          date:['20220101','20220102','20220103','20220104','20220105','20220106','20220107'],
          data:List
        },
        tableData:[
          {
            name:'oppo',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
          {
            name:'vivo',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
          {
            name:'apple',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
          {
            name:'sunxing',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
          {
            name:'mi',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
          {
            name:'oppo',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
          {
            name:'oppo',
            todayBuy:600,
            monthBuy:300,
            totalBuy:300000
          },
        ]
      }
    }
  }
}